-- V2__seed_currencies.sql
-- Seed ISO 4217 currency reference data

INSERT INTO currencies (code, name, symbol, decimal_places) VALUES
-- Major currencies
('GBP', 'British Pound', '£', 2),
('USD', 'US Dollar', '$', 2),
('EUR', 'Euro', '€', 2),
('JPY', 'Japanese Yen', '¥', 0),
('CHF', 'Swiss Franc', 'CHF', 2),
('CAD', 'Canadian Dollar', 'C$', 2),
('AUD', 'Australian Dollar', 'A$', 2),
('NZD', 'New Zealand Dollar', 'NZ$', 2),
('CNY', 'Chinese Yuan', '¥', 2),
('HKD', 'Hong Kong Dollar', 'HK$', 2),
('SGD', 'Singapore Dollar', 'S$', 2),
('SEK', 'Swedish Krona', 'kr', 2),
('NOK', 'Norwegian Krone', 'kr', 2),
('DKK', 'Danish Krone', 'kr', 2),
('KRW', 'South Korean Won', '₩', 0),
('INR', 'Indian Rupee', '₹', 2),
('BRL', 'Brazilian Real', 'R$', 2),
('ZAR', 'South African Rand', 'R', 2),
('MXN', 'Mexican Peso', 'Mex$', 2),
('RUB', 'Russian Ruble', '₽', 2),
('TRY', 'Turkish Lira', '₺', 2),
('PLN', 'Polish Zloty', 'zł', 2),
('THB', 'Thai Baht', '฿', 2),
('IDR', 'Indonesian Rupiah', 'Rp', 2),
('MYR', 'Malaysian Ringgit', 'RM', 2),
('PHP', 'Philippine Peso', '₱', 2),
('TWD', 'New Taiwan Dollar', 'NT$', 2),
('CZK', 'Czech Koruna', 'Kč', 2),
('HUF', 'Hungarian Forint', 'Ft', 2),
('ILS', 'Israeli New Shekel', '₪', 2),
('CLP', 'Chilean Peso', 'CLP$', 0),
('ARS', 'Argentine Peso', 'AR$', 2),
('COP', 'Colombian Peso', 'COL$', 2),
('PEN', 'Peruvian Sol', 'S/.', 2),
('SAR', 'Saudi Riyal', 'SAR', 2),
('AED', 'UAE Dirham', 'AED', 2),
('QAR', 'Qatari Riyal', 'QAR', 2),
('KWD', 'Kuwaiti Dinar', 'KWD', 3),
('BHD', 'Bahraini Dinar', 'BHD', 3),
('OMR', 'Omani Rial', 'OMR', 3),

-- Africa
('EGP', 'Egyptian Pound', 'E£', 2),
('NGN', 'Nigerian Naira', '₦', 2),
('KES', 'Kenyan Shilling', 'KSh', 2),
('GHS', 'Ghanaian Cedi', 'GH₵', 2),
('TZS', 'Tanzanian Shilling', 'TSh', 2),
('UGX', 'Ugandan Shilling', 'USh', 0),
('MAD', 'Moroccan Dirham', 'MAD', 2),
('TND', 'Tunisian Dinar', 'TND', 3),
('DZD', 'Algerian Dinar', 'DZD', 2),
('XOF', 'West African CFA Franc', 'CFA', 0),
('XAF', 'Central African CFA Franc', 'FCFA', 0),
('ZMW', 'Zambian Kwacha', 'ZK', 2),
('MWK', 'Malawian Kwacha', 'MK', 2),
('BWP', 'Botswana Pula', 'P', 2),
('MUR', 'Mauritian Rupee', 'Rs', 2),
('SCR', 'Seychellois Rupee', 'SCR', 2),
('ETB', 'Ethiopian Birr', 'Br', 2),
('RWF', 'Rwandan Franc', 'RF', 0),
('AOA', 'Angolan Kwanza', 'Kz', 2),
('MZN', 'Mozambican Metical', 'MT', 2),
('NAD', 'Namibian Dollar', 'N$', 2),
('SZL', 'Eswatini Lilangeni', 'E', 2),
('LSL', 'Lesotho Loti', 'M', 2),
('GMD', 'Gambian Dalasi', 'D', 2),
('SLL', 'Sierra Leonean Leone', 'Le', 2),
('LRD', 'Liberian Dollar', 'L$', 2),
('CVE', 'Cape Verdean Escudo', 'Esc', 2),
('BIF', 'Burundian Franc', 'FBu', 0),
('DJF', 'Djiboutian Franc', 'Fdj', 0),
('ERN', 'Eritrean Nakfa', 'Nfk', 2),
('SOS', 'Somali Shilling', 'Sh', 2),
('SDG', 'Sudanese Pound', 'SDG', 2),
('SSP', 'South Sudanese Pound', 'SSP', 2),
('CDF', 'Congolese Franc', 'FC', 2),
('MGF', 'Malagasy Ariary', 'Ar', 2),
('STN', 'São Tomé and Príncipe Dobra', 'Db', 2),
('MRU', 'Mauritanian Ouguiya', 'UM', 2),
('LYD', 'Libyan Dinar', 'LYD', 3),
('GNF', 'Guinean Franc', 'FG', 0),
('KMF', 'Comorian Franc', 'CF', 0),

-- Europe (non-EUR)
('ISK', 'Icelandic Krona', 'kr', 0),
('RON', 'Romanian Leu', 'lei', 2),
('BGN', 'Bulgarian Lev', 'лв', 2),
('HRK', 'Croatian Kuna', 'kn', 2),
('RSD', 'Serbian Dinar', 'din', 2),
('UAH', 'Ukrainian Hryvnia', '₴', 2),
('GEL', 'Georgian Lari', '₾', 2),
('AMD', 'Armenian Dram', '֏', 2),
('AZN', 'Azerbaijani Manat', '₼', 2),
('MDL', 'Moldovan Leu', 'L', 2),
('ALL', 'Albanian Lek', 'L', 2),
('MKD', 'Macedonian Denar', 'ден', 2),
('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 2),
('BYN', 'Belarusian Ruble', 'Br', 2),

-- Americas
('UYU', 'Uruguayan Peso', '$U', 2),
('PYG', 'Paraguayan Guarani', '₲', 0),
('BOB', 'Bolivian Boliviano', 'Bs.', 2),
('VES', 'Venezuelan Bolívar', 'Bs.S', 2),
('DOP', 'Dominican Peso', 'RD$', 2),
('GTQ', 'Guatemalan Quetzal', 'Q', 2),
('HNL', 'Honduran Lempira', 'L', 2),
('NIO', 'Nicaraguan Córdoba', 'C$', 2),
('CRC', 'Costa Rican Colón', '₡', 2),
('PAB', 'Panamanian Balboa', 'B/.', 2),
('JMD', 'Jamaican Dollar', 'J$', 2),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', 2),
('BBD', 'Barbadian Dollar', 'Bds$', 2),
('BSD', 'Bahamian Dollar', 'B$', 2),
('BZD', 'Belize Dollar', 'BZ$', 2),
('GYD', 'Guyanese Dollar', 'G$', 2),
('SRD', 'Surinamese Dollar', 'SRD', 2),
('HTG', 'Haitian Gourde', 'G', 2),
('CUP', 'Cuban Peso', '₱', 2),
('XCD', 'East Caribbean Dollar', 'EC$', 2),
('AWG', 'Aruban Florin', 'Afl.', 2),
('ANG', 'Netherlands Antillean Guilder', 'NAf.', 2),
('BMD', 'Bermudian Dollar', 'BD$', 2),
('KYD', 'Cayman Islands Dollar', 'CI$', 2),
('FKP', 'Falkland Islands Pound', 'FK£', 2),
('SVC', 'Salvadoran Colón', '₡', 2),

-- Asia & Oceania
('VND', 'Vietnamese Dong', '₫', 0),
('BDT', 'Bangladeshi Taka', '৳', 2),
('PKR', 'Pakistani Rupee', 'Rs', 2),
('LKR', 'Sri Lankan Rupee', 'Rs', 2),
('NPR', 'Nepalese Rupee', 'Rs', 2),
('MMK', 'Myanmar Kyat', 'K', 2),
('KHR', 'Cambodian Riel', '៛', 2),
('LAK', 'Lao Kip', '₭', 2),
('MNT', 'Mongolian Tugrik', '₮', 2),
('KZT', 'Kazakhstani Tenge', '₸', 2),
('UZS', 'Uzbekistani Som', 'UZS', 2),
('KGS', 'Kyrgyzstani Som', 'KGS', 2),
('TJS', 'Tajikistani Somoni', 'SM', 2),
('TMT', 'Turkmenistani Manat', 'T', 2),
('AFN', 'Afghan Afghani', '؋', 2),
('IRR', 'Iranian Rial', '﷼', 2),
('IQD', 'Iraqi Dinar', 'IQD', 3),
('JOD', 'Jordanian Dinar', 'JOD', 3),
('LBP', 'Lebanese Pound', 'L£', 2),
('SYP', 'Syrian Pound', 'S£', 2),
('YER', 'Yemeni Rial', 'YER', 2),
('BND', 'Brunei Dollar', 'B$', 2),
('FJD', 'Fijian Dollar', 'FJ$', 2),
('PGK', 'Papua New Guinean Kina', 'K', 2),
('WST', 'Samoan Tala', 'WS$', 2),
('TOP', 'Tongan Paʻanga', 'T$', 2),
('VUV', 'Vanuatu Vatu', 'VT', 0),
('SBD', 'Solomon Islands Dollar', 'SI$', 2),
('MVR', 'Maldivian Rufiyaa', 'Rf', 2),
('BTN', 'Bhutanese Ngultrum', 'Nu.', 2),
('MOP', 'Macanese Pataca', 'MOP$', 2),
('KPW', 'North Korean Won', '₩', 2),

-- Special / Precious metals
('XAU', 'Gold (troy ounce)', 'XAU', 4),
('XAG', 'Silver (troy ounce)', 'XAG', 4),
('XPT', 'Platinum (troy ounce)', 'XPT', 4),
('XPD', 'Palladium (troy ounce)', 'XPD', 4),

-- SDR
('XDR', 'IMF Special Drawing Rights', 'SDR', 4);